name: Deploy Application to ECS
on:
  workflow_dispatch:
env:
  AWS_REGION: us-east-1
  path_to_app: ./student-portal/src
  tag: ${{ github.sha }} 
  ecr_repository: app-portal
  ECS_APP_CONTAINER_NAME: app-cluster-container
  ECS_TASK_DEFINITION: app-cluster-task
  ECS_SERVICE: app-cluster-service
  ECS_CLUSTER: app-cluster

jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: configure AWS credentials 
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download task defination for web 
        if: ${{ github.ref == 'refs/heads/main'}}
        run: |
          aws ecs describe-task-definition --task-definition ${{ env.ECS_TASK_DEFINITION}} \
          --query taskDefinition > task-definition.json 
          ls -l task-definition.json 
          
      - name: Fill in the new image ID for web the Amazon ECS task definition 
        if: ${{ github.ref == 'refs/heads/main' }}
        id: task-def-web 
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with: 
          task-definition: task-definition.json
          container-name: ${{ env.ECS_APP_CONTAINER_NAME }}
          image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.aws_region }}.amazonaws.com/${{ env.ecr_repository }}:${{ github.sha}}

      - name: deploy app on Amazon ECS task definition 
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def-web.outputs.task-definition }} 
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true 